In [2]:
import numpy as np

#СОЗДАНИЕ МАССИВОВ

# Самый просто способ создать массив numpy - взять уже существующий list и передать в функцию np.array()
arr_1d = np.array([1, 2, 3])

# Теперь проверим 
#   - тип объекта c помощью функции type()
#   - размерность с помощью аттрибута .shape
#   - доступ по индексам, как у обычного list

# Для отладки можно выводить небольшие массивы прямо через print()

print(arr_1d)
print(type(arr_1d))
print(arr_1d.shape)
print(arr_1d[0])
print(arr_1d[2])
print(arr_1d[-1])

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1
3
3


In [4]:
# Теперь создадим двумерный массив с помощью тех же list
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_2d)
print(type(arr_2d))
print(arr_2d.shape)
print(arr_2d[0, 0])
print(arr_2d[1, 2])
print(arr_2d[1, 0])

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
1
6
4


In [5]:
# Создание массива фиксированного размера
np.ndarray((5, 3))

array([[1.10278614e-316, 1.01855798e-312, 1.01855798e-312],
       [9.54898106e-313, 1.14587773e-312, 1.06099790e-312],
       [1.23075756e-312, 1.01855798e-312, 1.08221785e-312],
       [9.76118064e-313, 1.20953760e-312, 1.16709769e-312],
       [1.03977794e-312, 4.44659081e-322, 0.00000000e+000]])

In [6]:
# Явное создание массива нулей
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# Создание массива, заполненного константным значением
np.full((3, 4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [8]:
# 2D массив с единичной главной диагональю
# (*) В этой функции размерность задается не кортежем, а отдельными аргументами
np.eye(3, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [9]:
# Создание массива нулей с такой же размерностью, как уже существующий
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

np.zeros_like(arr_2d)

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
# Создание массива единиц с такой же размерностью, как уже существующий
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

np.ones_like(arr_2d)

array([[1, 1, 1],
       [1, 1, 1]])

In [11]:
# Создание массива со случайными значениями в интервале [0; 1.0)
np.random.random((2,2))

array([[0.47050803, 0.26868974],
       [0.62523978, 0.26432209]])

In [12]:
# Аналог функции range
np.arange(start=1, stop=10, step=1.5)

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

In [13]:
# Также создание диапазона значений, но уже с заданием количества элементов
# (*) stop уже входит в создаваемый диапазон
np.linspace(start=1, stop=2, num=10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [15]:
# ХИТРАЯ ИНДЕКСАЦИЯ


# Для начала на простом списке (1D массива)
# Следующее создание массива можно заменить list(range(1, 11))
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Простая индексация
print(arr[0])
print(arr[-2])
print(arr[5])

1
9
6


In [16]:
# Получение части массива от 2го элемента до 6го (не включительно) 
#   с шагом 2 
print(arr[2:8:2])

[3, 5, 7]


In [17]:
# Если шаг не задан, то он равен единице (при этом второй раз : не пишется)
print(arr[2:8])

[3, 4, 5, 6, 7, 8]


In [18]:
# Шаг может быть и отрицательным (индексы меняются местами)
print(arr[8:2:-1])

[9, 8, 7, 6, 5, 4]


In [19]:
# Если не задавать index_start или index_end, 
#   то они будут равны индексу начала и конца массива
print(arr[2:])
print(arr[:8])

[3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8]


In [20]:
# Можно комбинировать один из индексов и шаг
print(arr[2::2])
print(arr[:8:3])

[3, 5, 7, 9]
[1, 4, 7]


In [21]:
# И не забываем, что все трюки работают и на запись
new_arr = list(range(1, 11))

new_arr[1:5] = arr[:4]
print(new_arr)

[1, 1, 2, 3, 4, 6, 7, 8, 9, 10]


In [22]:
# Не самая полезная, но все же запись (получить весь диапазон)
print(arr[:])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [23]:
# ЗАДАНИЕ 

print(arr[:5:-2])

#печатает индексы 10 и 8, проходясь с конца от 10 до 5 яндекса с шагом 2

[10, 8]


In [25]:
# ЗАДАНИЕ 

data = list(range(10))
print(data[::-1])

# TODO - [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [26]:
# ЗАДАНИЕ 

data = list(range(10))
print(data[1:8])

# TODO - [1, 2, 3, 4, 5, 6, 7]

[1, 2, 3, 4, 5, 6, 7]


In [27]:
# ХИТРАЯ ИНДЕКСАЦИЯ В МАТРИЦАХ

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
# Получим вторую строку массива
print(arr[2])
print(arr[2, :])

[ 9 10 11 12]
[ 9 10 11 12]


In [29]:
# Получим первую колонку массива
print(arr[:, 1])

[ 2  6 10]


In [30]:
# Получить первые два элемента (первые две колонки) первого ряда
print(arr[1, :2])

[5 6]


In [31]:
# Можно повторять целые части массива
#   (но при этом должны соотноситься размерности)
# ndarray.copy() - функция копирования массива
# Копируем, чтобы не изменить оригинальный
new_arr = arr.copy()
print(arr)

new_arr[2, :] = arr[1, :]
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [32]:
# При этом, такая индексация - это новый массив со своей размерностью.
print(arr[:2, :2])
print(arr[:2, :2].shape)

[[1 2]
 [5 6]]
(2, 2)


In [33]:
# В качестве индексов можно также задавать другие массивы
# Получаем первую и последнюю колонки
print(arr[:, [0, -1]])

[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [34]:
# И таким образом никто не заставляет писать в том же порядке индексы
# Перемешаем ряды
print(arr[[2, 0, 1], :])

[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [35]:
# Также, можно комбинировать способы задания
print(arr[[2, 0], [1, 3]])
# То же самое, только первая запись дает массив
print(arr[2, 1], arr[0, 3])

[10  4]
10 4


In [36]:
# Создаем список возможных индексов для рядов массива
row_indices = list(range(arr.shape[0]))
print(row_indices)

# Переворачиваем его
row_indices = list(reversed(row_indices))
print(row_indices)

# Используем для индексации
print('----------------')
print(arr[row_indices])

[0, 1, 2]
[2, 1, 0]
----------------
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [49]:
# ЗАДАНИЕ 

data = np.random.randint(low=0, high=10, size=(6, 7))
print(data)
print('----------------')
print(data[1:5, 1:6])


# TODO - центральная часть массива размером (4, 5)

[[8 1 2 5 3 3 0]
 [3 1 5 9 6 8 6]
 [9 2 8 0 1 2 1]
 [2 9 1 8 9 2 5]
 [5 8 9 2 5 4 4]
 [6 5 8 8 7 5 9]]
----------------
[[1 5 9 6 8]
 [2 8 0 1 2]
 [9 1 8 9 2]
 [8 9 2 5 4]]


In [52]:
# ЗАДАНИЕ 

data = np.random.randint(low=0, high=10, size=(3, 6))
print(data)
print('----------------')
print(data[:, np.random.permutation(6)])

# TODO - такой же массив, но со случайной перестановкой колонок

[[3 0 5 1 8 6]
 [5 8 1 2 7 1]
 [4 8 0 9 8 9]]
----------------
[[8 1 3 6 0 5]
 [7 2 5 1 8 1]
 [8 9 4 9 8 0]]


In [53]:
# ТИПЫ ДАННЫХ В МАССИВАХ

# Создадим массив без задания типа - тип будет определен автоматически
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr.dtype)

# int, так как все элементы являются целочисленными

int64


In [54]:
# Изменим один элемент на вещественный
arr = np.array([[1.5, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr.dtype)

# Один из элементов float, поэтому весь массив будет float

float64


In [55]:
# Зададим явно тип массива
# Хоть массив и содержит вещественные числа
# мы создаем массив целочисленных, что приводит
# к округлению
arr = np.array([[1.1, 1.6, 2.4], [-1.7, 2.6, -1.2]], dtype=int)
print(arr)
print(arr.dtype)

[[ 1  1  2]
 [-1  2 -1]]
int64


In [56]:
# Создаем массив вещественных
arr = np.array([[1.1, 1.6, 2.4], [-1.7, 2.6, -1.2]])
print(arr)
print(arr.dtype)
print('----------')
# Но в какой-то момент нам нужно привести массив к целочисленным
# Воспользуемся методом ndarray.astype()
arr = arr.astype(int)
print(arr)
print(arr.dtype)

[[ 1.1  1.6  2.4]
 [-1.7  2.6 -1.2]]
float64
----------
[[ 1  1  2]
 [-1  2 -1]]
int64


In [57]:
# При этом попытки записать в целочисленный массив 
# вещественное число приводят к округлению
arr = np.array([[1.1, 1.6, 2.4], [-1.7, 2.6, -1.2]], dtype=int)
print(arr)

arr[0, 1] = 10.12
print(arr)

[[ 1  1  2]
 [-1  2 -1]]
[[ 1 10  2]
 [-1  2 -1]]


In [58]:
# БУЛЕВЫ ОПЕРАЦИИ НАД МАССИВАМИ

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [59]:
# Произведем сравнение с числом
result = arr > 6
print(result)
print(result.dtype)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
bool


In [60]:
result_1 = arr > 6
result_2 = arr < 10
print(result_1)
print(result_2)

print('----------')
# Следующие две операции идентичны, но для второй скобки обязательны!
print(result_1 & result_2)
print((arr > 6) & (arr < 10))

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True False False False]]
----------
[[False False False False]
 [False False  True  True]
 [ True False False False]]
[[False False False False]
 [False False  True  True]
 [ True False False False]]


In [71]:
# ЗАДАНИЕ

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

result = np.logical_and(arr > 5, arr < 8)
np.any(result)

# TODO - определить, имеется ли в массиве хотя бы один элемент, 
#           отвечающий условию больше пяти и меньше восьми

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


True

In [72]:
# БОЛЬШЕ ИНДЕКСАЦИИ

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Получим маску и воспользуемся ею для индексации
mask = arr > 6
print(mask)
print(arr[mask])

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 7  8  9 10 11 12]


In [73]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.flatten())

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [76]:
# ОПЕРАЦИИ С МАССИВАМИ

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Сложение
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [77]:
# Вычитание
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [78]:
# Поэлементное умножение
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [79]:
# Поэлементное деление
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [80]:
# Вычисление корня каждого элемента
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [81]:
# Умножение матрицы на скаляр - релизуется как поэлементное перемножение 
k = 1.5

print(k*x)

[[1.5 3. ]
 [4.5 6. ]]


In [82]:
v = np.array([1, 2])

In [83]:
# Матричное умножение реализуется через оператор @ или функцию np.dot() 
#   или метод ndarray.dot()
# Для умножения матрица-вектор

print(x @ v)
print(x.dot(v))
print(np.dot(x, v))

[ 5. 11.]
[ 5. 11.]
[ 5. 11.]


In [84]:
# Двух векторов
w = np.array([3, 4])

print(w @ v)
print(w.dot(v))
print(np.dot(w, v))

11
11
11


In [85]:
# Так и для перемножения матриц
print(x @ y)
print(x.dot(y))
print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [86]:
# Для транспонирования можно воспользоваться атрибутом ndarray.T
#   или функцией np.transpose()
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.shape)
print('--------')
print(np.transpose(x))
print(x.T)
print(x.T.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
--------
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [87]:
# ОПЕРАЦИИ ПО ОСЯМ

x = np.array([[1, 2, 3], [5, 4, 3]])
print(x)

[[1 2 3]
 [5 4 3]]


In [88]:
# Возьмем среднее значение всего массива
print(np.mean(x))
print(np.mean(x, axis=None))

3.0
3.0


In [89]:
# Получим сумму значений всего массива
print(np.sum(x))
print(np.sum(x, axis=None))

18
18


In [90]:
# Получим среднее по каждому столбцу
print(np.mean(x, axis=0))

# Получим среднее по каждой строке
print(np.mean(x, axis=1))

[3. 3. 3.]
[2. 4.]


In [95]:
# ЗАДАНИЕ

data = np.random.randint(low=0, high=5, size=(3, 6))
print(data)
print('--------')
print(np.sum(data, axis=0))

# TODO - вектор сумм элементов по каждому столбцу

[[4 1 4 0 1 2]
 [4 0 0 2 3 0]
 [2 0 3 3 2 0]]
--------
[10  1  7  5  6  2]


In [96]:
# BROADCASTING (ТРАНСЛЯЦИЯ)

vec = np.arange(4)
mtrx = np.ones((3, 4))
print(vec)
print(mtrx)

[0 1 2 3]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [97]:
result = np.empty_like(mtrx)

for i_row in range(mtrx.shape[0]):
    result[i_row,:] = mtrx[i_row,:] * vec

print(result)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [98]:
# Функция np.tile() повторяет массив то количество раз и по тем осям,
#   который заданы в аргументе reps
vec_m = np.tile(vec, reps=(3, 1))
print(vec_m)
print(vec_m * mtrx)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [99]:
# Умножение, используя броадкастинг
print(vec * mtrx)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [100]:
print(2 * mtrx)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [101]:
x = np.ones((4, 1, 1))
y = np.random.randint(0, 5, size=(4, 3, 2))

print((x*y).shape)

(4, 3, 2)


In [104]:
x = np.ones((3, 1))
y = np.random.randint(0, 5, size=(4, 3, 2))

print((x*y).shape)

(4, 3, 2)


In [105]:
x = np.ones((1, 3, 2))
y = np.random.randint(0, 5, size=(5, 1, 2))

print((x*y).shape)

(5, 3, 2)


In [106]:
# ИЗМЕНЕНИЕ РАЗМЕРОВ МАССИВА (RESHAPE)

arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [107]:
mtrx = np.ndarray((4, 5), dtype=np.int32)
mtrx[0, :] = arr[:5]
mtrx[1, :] = arr[5:10]
mtrx[2, :] = arr[10:15]
mtrx[3, :] = arr[15:]

print(mtrx)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [108]:
print(arr.reshape((4, 5)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [109]:
print(arr.reshape((2, 10)))
print(arr.reshape((5, 4)))
print(arr.reshape((20, 1)))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [110]:
print(arr.reshape((4, -1)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [111]:
# ОБЪЕДИНЕНИЕ МАССИВОВ

x = np.arange(10).reshape((2, 5))
y = np.arange(15).reshape((3, 5))

print(x)
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [112]:
print(np.concatenate((x, y), axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [115]:
# ЗАДАНИЕ

x = np.arange(9).reshape((3, 3))
y = np.arange(12).reshape((3, 4))
z = np.arange(15).reshape((3, 5))

print(x)
print(y)
print(z)
print('--------')
print(np.concatenate((x, y, z), axis=1))

# TODO - получите объединенный массив:
# [[ 0  1  2  0  1  2  3  0  1  2  3  4]
#  [ 3  4  5  4  5  6  7  5  6  7  8  9]
#  [ 6  7  8  8  9 10 11 10 11 12 13 14]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
--------
[[ 0  1  2  0  1  2  3  0  1  2  3  4]
 [ 3  4  5  4  5  6  7  5  6  7  8  9]
 [ 6  7  8  8  9 10 11 10 11 12 13 14]]


In [135]:
# ЗАДАНИЕ

x = np.arange(1, 10).reshape((3, 3))
print(x)
print('--------')
y = np.ones((3,1), dtype=int)
print(y)
print('--------')
print(np.concatenate((y, x), axis=1))

# TODO - получить матрицу со столбцом единиц слева
# [[1 1 2 3]
#  [1 4 5 6]
#  [1 7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------
[[1]
 [1]
 [1]]
--------
[[1 1 2 3]
 [1 4 5 6]
 [1 7 8 9]]


In [136]:
# СОРТИРОВКА МАССИВА

unsorted_arr = np.array([2, 4, 5, 1, 2, 7, 5, 0, -1, 3, 5])
sorted_arr = np.sort(unsorted_arr)

print(unsorted_arr)
print(sorted_arr)


[ 2  4  5  1  2  7  5  0 -1  3  5]
[-1  0  1  2  2  3  4  5  5  5  7]


In [137]:
sorted_indices = np.argsort(unsorted_arr)
print(sorted_indices)

# А теперь воспользуемся индексами и отобразим исходный массив с индексацией
print(unsorted_arr[sorted_indices])

[ 8  7  3  0  4  9  1  2  6 10  5]
[-1  0  1  2  2  3  4  5  5  5  7]


In [22]:
# ЗАДАНИЕ 

arr = np.array([
    [11, -1, 1, 3, 5],
    [6, 1, 0, -1, 10],
    [1, 3, 2, 3, 6],
    [5, 2, 7, 8, 9],
])

print(arr)
print('--------')
sorted_indices = np.argsort(arr, axis=0)
print(sorted_indices)
print('--------')
print('Максимальный:')
print(sorted_indices[3,:])
print('Минимальный:')
print(sorted_indices[0,:])

# TODO - напишите код поиска индексов максимальных/минимальных 
#           элементов в массиве по столбцам: [0 2 3 3 1]/[2 0 1 1 0]

[[11 -1  1  3  5]
 [ 6  1  0 -1 10]
 [ 1  3  2  3  6]
 [ 5  2  7  8  9]]
--------
[[2 0 1 1 0]
 [3 1 0 0 2]
 [1 3 2 2 3]
 [0 2 3 3 1]]
--------
Максимальный:
[0 2 3 3 1]
Минимальный:
[2 0 1 1 0]


In [27]:
# ЗАДАНИЕ

arr = np.array([
    [11, 2, 1, 3, 5],
    [6, 2, 0, -1, 10],
    [1, 3, 2, 3, 5],
    [5, 2, 7, 8, 9],
])
print(arr)
print('--------')
sorted_arr = np.sort(arr, axis = 0)
print(sorted_arr)

# TODO - напишите код сортировки:
# [[ 1  2  0 -1  5]
#  [ 5  2  1  3  5]
#  [ 6  2  2  3  9]
#  [11  3  7  8 10]]

[[11  2  1  3  5]
 [ 6  2  0 -1 10]
 [ 1  3  2  3  5]
 [ 5  2  7  8  9]]
--------
[[ 1  2  0 -1  5]
 [ 5  2  1  3  5]
 [ 6  2  2  3  9]
 [11  3  7  8 10]]


In [32]:
# ЗАДАЧКИ

# TODO - создайте массив (5,7) со случайными целочисленными элементами [-10;20]
arr = np.random.randint(low=-10, high=20, size=(5,7))
print(arr)

[[  7  -8  -1  18  15  -2  12]
 [  1   1  12  -1   9   4 -10]
 [ 19  15  -5   9  10  13  -1]
 [ 13  19   4  17   6   7  -5]
 [ -5   5  14  16  -2   1  11]]


In [44]:
data = np.arange(1, 16).reshape((3, 5))
print(data)
print('--------')
arr_zero_stl = np.concatenate(((np.zeros((3,1), dtype=int)), data,(np.zeros((3,1), dtype=int))), axis=1)
arr_zero = np.concatenate(((np.zeros((1,7), dtype=int)), arr_zero_stl,(np.zeros((1,7), dtype=int))), axis=0)
print(arr_zero)

# TODO - реализуйте добавление нулей со всех сторон массива:
# [[ 0  0  0  0  0  0  0]
#  [ 0  1  2  3  4  5  0]
#  [ 0  6  7  8  9 10  0]
#  [ 0 11 12 13 14 15  0]
#  [ 0  0  0  0  0  0  0]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
--------
[[ 0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  0]
 [ 0  6  7  8  9 10  0]
 [ 0 11 12 13 14 15  0]
 [ 0  0  0  0  0  0  0]]


In [47]:
data = np.arange(1, 16).reshape((3, 5))
print(data)
print('--------')
data = np.clip(data,2,6)
print(data)

# TODO - ограничьте значения массива
# [[2 2 3 4 5]
#  [6 6 6 6 6]
#  [6 6 6 6 6]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
--------
[[2 2 3 4 5]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [96]:
import math as mt


data = np.full((3, 5), fill_value=2, dtype=np.int32)
print(data)
print('--------')
vec = np.arange(5)
n = np.tile(vec, reps=(3, 1))
print(n)
print('--------')
result = np.power(data,n)
print(result)

# TODO - возведите значения в колонках в степень индекса колонки
# [[ 1  2  4  8 16]
#  [ 1  2  4  8 16]
#  [ 1  2  4  8 16]]

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
--------
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
--------
[[ 1  2  4  8 16]
 [ 1  2  4  8 16]
 [ 1  2  4  8 16]]


In [98]:
data = np.full((3, 5), fill_value=2, dtype=np.int32)
print(data)
print('--------')
vec = np.arange(5)
n = np.tile(vec, reps=(3, 1))
print(n)
print('--------')
result = np.multiply(data,n)
print(result)
# TODO - Умножьте каждый столбец на свой индекс
# [[0 2 4 6 8]
#  [0 2 4 6 8]
#  [0 2 4 6 8]]

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
--------
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
--------
[[0 2 4 6 8]
 [0 2 4 6 8]
 [0 2 4 6 8]]


In [126]:
data = np.repeat(np.arange(1, 8), 4).reshape(7, 4)
vec = np.array([1, 2, 1, 2])
print(data)
print('--------')
data_vec = data[::2]*vec
print(data_vec)
print('--------')

#i=0
#j=0
#for i in range(6):
#  for j in range(3):
#    data[i,:] = data_vec[j,:]
#    i +=2
#    j +=1

data[0,:] = data_vec[0,:]
data[2,:] = data_vec[1,:]
data[4,:] = data_vec[2,:]
data[6,:] = data_vec[3,:]


print(data)


# TODO - умножьте каждый четный ряд в матрице на вектор
# [[ 1  2  1  2]
#  [ 2  2  2  2]
#  [ 3  6  3  6]
#  [ 4  4  4  4]
#  [ 5 10  5 10]
#  [ 6  6  6  6]
#  [ 7 14  7 14]]

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]
--------
[[ 1  2  1  2]
 [ 3  6  3  6]
 [ 5 10  5 10]
 [ 7 14  7 14]]
--------
[[ 1  2  1  2]
 [ 2  2  2  2]
 [ 3  6  3  6]
 [ 4  4  4  4]
 [ 5 10  5 10]
 [ 6  6  6  6]
 [ 7 14  7 14]]


In [198]:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 4, 24, 24, 28,  3, 40]])
print(data)

print('--------')
sorted_indices = np.argsort(data, axis=1)
print(sorted_indices)
print('--------')
print('Максимальный:')

result = sorted_indices[0:4, 4:6]
result = np.flip(result, axis=1)
print(result)


# TODO - определите индексы двух наибольших элементов по каждому ряду
# [[4 1]
#  [1 2]
#  [3 1]
#  [5 3]]

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [ 4 24 24 28  3 40]]
--------
[[2 5 3 0 1 4]
 [3 0 5 4 2 1]
 [4 0 2 5 1 3]
 [4 0 1 2 3 5]]
--------
Максимальный:
[[4 1]
 [1 2]
 [3 1]
 [5 3]]


In [226]:
import random as rd

data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
print('--------')
new_data=data[:,[rd.randint(0, len(data)),rd.randint(0, len(data))]]
print(new_data)


# TODO - выберите случайные две колонки из массива
# *Например,
# [[22  8]
#  [25 15]
#  [16  9]
#  [24 40]]

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [ 4 24 24 28  3 40]]
--------
[[ 2 14]
 [23  3]
 [ 9 22]
 [24 28]]


In [252]:
data = np.arange(9).reshape(3, 3)
print(data)
print('--------')
new_data = np.tile(data, reps=(3, 1))
new_data = np.concatenate((new_data[-1:,:], new_data), axis = 0)
new_data = np.random.permutation(new_data)
print(new_data)

# TODO - создайте массив из повторяющихся рядов размером (10, 3)
# *Например,
# [[3 4 5]
#  [6 7 8]
#  [0 1 2]
#  [6 7 8]
#  [3 4 5]
#  [6 7 8]
#  [6 7 8]
#  [6 7 8]
#  [6 7 8]
#  [0 1 2]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------
[[6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [0 1 2]
 [6 7 8]]


In [255]:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 14, 9,  33, 21,  7,  6],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
print('--------')
new_data = data[[1,2,3],:]
new_data = new_data[:,[2,4]]
print(new_data)
# TODO - соберите матрицу из конкретных элементов массива
# [[23 22]
#  [ 9  0]
#  [33  7]]

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [14  9 33 21  7  6]
 [ 4 24 24 28  3 40]]
--------
[[23 22]
 [ 9  0]
 [33  7]]


In [285]:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 14, 9,  33, 21,  7,  6],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
print('--------')
arr_1 = data[:,[-1]]
arr_1 = np.transpose(list(reversed(arr_1.flatten())))
print(arr_1)
print('--------')
arr_2 = data[:,[-2]]
arr_2 = np.transpose(list(reversed(arr_2.flatten())))
print(arr_2)
print('--------')
data[:,-2]=arr_2
data[:,-1]=arr_1
print(data)

# TODO - инвертируйте порядок последних двух колонок
# [[20 22  2 14  3 40]
#  [ 7 25 23  3  7  6]
#  [ 8 16  9 22  0  9]
#  [14  9 33 21 22 15]
#  [ 4 24 24 28 25  8]]

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [14  9 33 21  7  6]
 [ 4 24 24 28  3 40]]
--------
[40  6  9 15  8]
--------
[ 3  7  0 22 25]
--------
[[20 22  2 14  3 40]
 [ 7 25 23  3  7  6]
 [ 8 16  9 22  0  9]
 [14  9 33 21 22 15]
 [ 4 24 24 28 25  8]]
